# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishList_app', '0003_auto_20170531_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_list',
            field=models.BooleanField(default=False),
        ),
    ]
